# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazygit < Formula
  desc "A simple terminal UI for git commands, written in Go"
  homepage "https://github.com/jesseduffield/lazygit/"
  version "0.40.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Darwin_arm64.tar.gz"
      sha256 "2857416d0d5b21c28a69850b068e072d0064f158a5b6fcfa97a3df8789f5de7f"

      def install
        bin.install "lazygit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Darwin_x86_64.tar.gz"
      sha256 "0000cc8ae3a4818af71bbb949674cc6874b9ba95dfa91ff15290f49cb04573fa"

      def install
        bin.install "lazygit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_arm64.tar.gz"
      sha256 "d88972818ce67dea2832e4f275b06975188f49716de13c4e452918212fd31616"

      def install
        bin.install "lazygit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_armv6.tar.gz"
      sha256 "f37baac1b1cffef5173c337e401d5f73571240bdf97a6b78e471a5ae7938cae1"

      def install
        bin.install "lazygit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_x86_64.tar.gz"
      sha256 "ff05cb8ebd0785ce220975e5cd394bc200424d9a58727fa81e0bbb3828db7ff1"

      def install
        bin.install "lazygit"
      end
    end
  end
end
